Zack Branch 1
kpamela/StudyRing pull request #117
Opened 2017-03-27 23:13 UTC by Zackkogan

changed return type from array to string. hopefully this will fix the
bugs #43

2017-03-28 01:02 UTC, tusmanakhter requested changes
This should be added to the events collection not the rings collection

2017-03-28 13:20 UTC, kpamela requested changes

2017-03-28 13:20 UTC, kpamela commented on StudyRingMeteor/collections/rings/rings.js
> +            if (this.isInsert && (!this.isSet || this.value.length === 0)) {
This line is not appropriate for location attributes

2017-03-31 20:21 UTC, tusmanakhter commented
Old request.

2017-03-31 20:21 UTC, closed without merging