Zack Branch 1
kpamela/StudyRing pull request #98
Opened 2017-03-21 17:46 UTC by Zackkogan

added location parameter for rings #43 

requesting review from others to test additions to the code

2017-03-21 18:48 UTC, kpamela requested changes
Location was added in rings.js, move to the events collection please.

2017-03-21 18:48 UTC, kpamela commented on StudyRingMeteor/collections/rings/rings.js
> +            type: "hidden"
Do not make it hidden or else, event location will not be possible to set during its creation

2017-03-21 18:48 UTC, kpamela commented on StudyRingMeteor/collections/rings/rings.js
> +            if (this.isInsert && (!this.isSet || this.value.length === 0)) {
Not necessary, unless there is a future implementation of multiple locations

2017-03-22 03:39 UTC, Lordofsnails commented
Brah....your code is buggy, you are missing the whole front end stuff, so basically you added a field in the collection, but no where did you request a user to input the actual location...In other words location isn t even set, hence i am failing this pull request since it does not fulfill the actual criteria

2017-03-22 14:27 UTC, kpamela commented
@Lordofsnails usually quickForm takes care of user input, its just in the wrong collection

2017-03-24 15:16 UTC, BGoldwax commented
Failed Travis CI tests

2017-03-24 15:16 UTC, closed without merging